// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl_chair.proto

#ifndef PROTOBUF_ctrl_5fchair_2eproto__INCLUDED
#define PROTOBUF_ctrl_5fchair_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ctrl_common_param_tbox.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ctrl_5fchair_2eproto();
void protobuf_AssignDesc_ctrl_5fchair_2eproto();
void protobuf_ShutdownFile_ctrl_5fchair_2eproto();

class CtrlChairMessage;

// ===================================================================

class CtrlChairMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CtrlChairMessage) */ {
 public:
  CtrlChairMessage();
  virtual ~CtrlChairMessage();

  CtrlChairMessage(const CtrlChairMessage& from);

  inline CtrlChairMessage& operator=(const CtrlChairMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlChairMessage& default_instance();

  void Swap(CtrlChairMessage* other);

  // implements Message ----------------------------------------------

  inline CtrlChairMessage* New() const { return New(NULL); }

  CtrlChairMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlChairMessage& from);
  void MergeFrom(const CtrlChairMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlChairMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CtrlCommonParamTbox common_param = 1;
  bool has_common_param() const;
  void clear_common_param();
  static const int kCommonParamFieldNumber = 1;
  const ::CtrlCommonParamTbox& common_param() const;
  ::CtrlCommonParamTbox* mutable_common_param();
  ::CtrlCommonParamTbox* release_common_param();
  void set_allocated_common_param(::CtrlCommonParamTbox* common_param);

  // optional .CtrlCommonInfo chair_ctrl_info = 2;
  bool has_chair_ctrl_info() const;
  void clear_chair_ctrl_info();
  static const int kChairCtrlInfoFieldNumber = 2;
  const ::CtrlCommonInfo& chair_ctrl_info() const;
  ::CtrlCommonInfo* mutable_chair_ctrl_info();
  ::CtrlCommonInfo* release_chair_ctrl_info();
  void set_allocated_chair_ctrl_info(::CtrlCommonInfo* chair_ctrl_info);

  // @@protoc_insertion_point(class_scope:CtrlChairMessage)
 private:
  inline void set_has_common_param();
  inline void clear_has_common_param();
  inline void set_has_chair_ctrl_info();
  inline void clear_has_chair_ctrl_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::CtrlCommonParamTbox* common_param_;
  ::CtrlCommonInfo* chair_ctrl_info_;
  friend void  protobuf_AddDesc_ctrl_5fchair_2eproto();
  friend void protobuf_AssignDesc_ctrl_5fchair_2eproto();
  friend void protobuf_ShutdownFile_ctrl_5fchair_2eproto();

  void InitAsDefaultInstance();
  static CtrlChairMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlChairMessage

// optional .CtrlCommonParamTbox common_param = 1;
inline bool CtrlChairMessage::has_common_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlChairMessage::set_has_common_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlChairMessage::clear_has_common_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlChairMessage::clear_common_param() {
  if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
  clear_has_common_param();
}
inline const ::CtrlCommonParamTbox& CtrlChairMessage::common_param() const {
  // @@protoc_insertion_point(field_get:CtrlChairMessage.common_param)
  return common_param_ != NULL ? *common_param_ : *default_instance_->common_param_;
}
inline ::CtrlCommonParamTbox* CtrlChairMessage::mutable_common_param() {
  set_has_common_param();
  if (common_param_ == NULL) {
    common_param_ = new ::CtrlCommonParamTbox;
  }
  // @@protoc_insertion_point(field_mutable:CtrlChairMessage.common_param)
  return common_param_;
}
inline ::CtrlCommonParamTbox* CtrlChairMessage::release_common_param() {
  // @@protoc_insertion_point(field_release:CtrlChairMessage.common_param)
  clear_has_common_param();
  ::CtrlCommonParamTbox* temp = common_param_;
  common_param_ = NULL;
  return temp;
}
inline void CtrlChairMessage::set_allocated_common_param(::CtrlCommonParamTbox* common_param) {
  delete common_param_;
  common_param_ = common_param;
  if (common_param) {
    set_has_common_param();
  } else {
    clear_has_common_param();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlChairMessage.common_param)
}

// optional .CtrlCommonInfo chair_ctrl_info = 2;
inline bool CtrlChairMessage::has_chair_ctrl_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlChairMessage::set_has_chair_ctrl_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlChairMessage::clear_has_chair_ctrl_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlChairMessage::clear_chair_ctrl_info() {
  if (chair_ctrl_info_ != NULL) chair_ctrl_info_->::CtrlCommonInfo::Clear();
  clear_has_chair_ctrl_info();
}
inline const ::CtrlCommonInfo& CtrlChairMessage::chair_ctrl_info() const {
  // @@protoc_insertion_point(field_get:CtrlChairMessage.chair_ctrl_info)
  return chair_ctrl_info_ != NULL ? *chair_ctrl_info_ : *default_instance_->chair_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlChairMessage::mutable_chair_ctrl_info() {
  set_has_chair_ctrl_info();
  if (chair_ctrl_info_ == NULL) {
    chair_ctrl_info_ = new ::CtrlCommonInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlChairMessage.chair_ctrl_info)
  return chair_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlChairMessage::release_chair_ctrl_info() {
  // @@protoc_insertion_point(field_release:CtrlChairMessage.chair_ctrl_info)
  clear_has_chair_ctrl_info();
  ::CtrlCommonInfo* temp = chair_ctrl_info_;
  chair_ctrl_info_ = NULL;
  return temp;
}
inline void CtrlChairMessage::set_allocated_chair_ctrl_info(::CtrlCommonInfo* chair_ctrl_info) {
  delete chair_ctrl_info_;
  chair_ctrl_info_ = chair_ctrl_info;
  if (chair_ctrl_info) {
    set_has_chair_ctrl_info();
  } else {
    clear_has_chair_ctrl_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlChairMessage.chair_ctrl_info)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ctrl_5fchair_2eproto__INCLUDED
