// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl_private_information.proto

#ifndef PROTOBUF_ctrl_5fprivate_5finformation_2eproto__INCLUDED
#define PROTOBUF_ctrl_5fprivate_5finformation_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ctrl_common_param_tbox.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ctrl_5fprivate_5finformation_2eproto();
void protobuf_AssignDesc_ctrl_5fprivate_5finformation_2eproto();
void protobuf_ShutdownFile_ctrl_5fprivate_5finformation_2eproto();

class CtrlPrivateInformationMessage;
class PrivateInfoStateInfo;

// ===================================================================

class CtrlPrivateInformationMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CtrlPrivateInformationMessage) */ {
 public:
  CtrlPrivateInformationMessage();
  virtual ~CtrlPrivateInformationMessage();

  CtrlPrivateInformationMessage(const CtrlPrivateInformationMessage& from);

  inline CtrlPrivateInformationMessage& operator=(const CtrlPrivateInformationMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlPrivateInformationMessage& default_instance();

  void Swap(CtrlPrivateInformationMessage* other);

  // implements Message ----------------------------------------------

  inline CtrlPrivateInformationMessage* New() const { return New(NULL); }

  CtrlPrivateInformationMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlPrivateInformationMessage& from);
  void MergeFrom(const CtrlPrivateInformationMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlPrivateInformationMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CtrlCommonParamTbox common_param = 1;
  bool has_common_param() const;
  void clear_common_param();
  static const int kCommonParamFieldNumber = 1;
  const ::CtrlCommonParamTbox& common_param() const;
  ::CtrlCommonParamTbox* mutable_common_param();
  ::CtrlCommonParamTbox* release_common_param();
  void set_allocated_common_param(::CtrlCommonParamTbox* common_param);

  // optional .CtrlCommonInfo private_info_ctrl_info = 2;
  bool has_private_info_ctrl_info() const;
  void clear_private_info_ctrl_info();
  static const int kPrivateInfoCtrlInfoFieldNumber = 2;
  const ::CtrlCommonInfo& private_info_ctrl_info() const;
  ::CtrlCommonInfo* mutable_private_info_ctrl_info();
  ::CtrlCommonInfo* release_private_info_ctrl_info();
  void set_allocated_private_info_ctrl_info(::CtrlCommonInfo* private_info_ctrl_info);

  // optional .PrivateInfoStateInfo private_info_state_info = 3;
  bool has_private_info_state_info() const;
  void clear_private_info_state_info();
  static const int kPrivateInfoStateInfoFieldNumber = 3;
  const ::PrivateInfoStateInfo& private_info_state_info() const;
  ::PrivateInfoStateInfo* mutable_private_info_state_info();
  ::PrivateInfoStateInfo* release_private_info_state_info();
  void set_allocated_private_info_state_info(::PrivateInfoStateInfo* private_info_state_info);

  // @@protoc_insertion_point(class_scope:CtrlPrivateInformationMessage)
 private:
  inline void set_has_common_param();
  inline void clear_has_common_param();
  inline void set_has_private_info_ctrl_info();
  inline void clear_has_private_info_ctrl_info();
  inline void set_has_private_info_state_info();
  inline void clear_has_private_info_state_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::CtrlCommonParamTbox* common_param_;
  ::CtrlCommonInfo* private_info_ctrl_info_;
  ::PrivateInfoStateInfo* private_info_state_info_;
  friend void  protobuf_AddDesc_ctrl_5fprivate_5finformation_2eproto();
  friend void protobuf_AssignDesc_ctrl_5fprivate_5finformation_2eproto();
  friend void protobuf_ShutdownFile_ctrl_5fprivate_5finformation_2eproto();

  void InitAsDefaultInstance();
  static CtrlPrivateInformationMessage* default_instance_;
};
// -------------------------------------------------------------------

class PrivateInfoStateInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PrivateInfoStateInfo) */ {
 public:
  PrivateInfoStateInfo();
  virtual ~PrivateInfoStateInfo();

  PrivateInfoStateInfo(const PrivateInfoStateInfo& from);

  inline PrivateInfoStateInfo& operator=(const PrivateInfoStateInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PrivateInfoStateInfo& default_instance();

  void Swap(PrivateInfoStateInfo* other);

  // implements Message ----------------------------------------------

  inline PrivateInfoStateInfo* New() const { return New(NULL); }

  PrivateInfoStateInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PrivateInfoStateInfo& from);
  void MergeFrom(const PrivateInfoStateInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PrivateInfoStateInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lock_state = 1;
  bool has_lock_state() const;
  void clear_lock_state();
  static const int kLockStateFieldNumber = 1;
  ::google::protobuf::int32 lock_state() const;
  void set_lock_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PrivateInfoStateInfo)
 private:
  inline void set_has_lock_state();
  inline void clear_has_lock_state();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 lock_state_;
  friend void  protobuf_AddDesc_ctrl_5fprivate_5finformation_2eproto();
  friend void protobuf_AssignDesc_ctrl_5fprivate_5finformation_2eproto();
  friend void protobuf_ShutdownFile_ctrl_5fprivate_5finformation_2eproto();

  void InitAsDefaultInstance();
  static PrivateInfoStateInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlPrivateInformationMessage

// optional .CtrlCommonParamTbox common_param = 1;
inline bool CtrlPrivateInformationMessage::has_common_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlPrivateInformationMessage::set_has_common_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlPrivateInformationMessage::clear_has_common_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlPrivateInformationMessage::clear_common_param() {
  if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
  clear_has_common_param();
}
inline const ::CtrlCommonParamTbox& CtrlPrivateInformationMessage::common_param() const {
  // @@protoc_insertion_point(field_get:CtrlPrivateInformationMessage.common_param)
  return common_param_ != NULL ? *common_param_ : *default_instance_->common_param_;
}
inline ::CtrlCommonParamTbox* CtrlPrivateInformationMessage::mutable_common_param() {
  set_has_common_param();
  if (common_param_ == NULL) {
    common_param_ = new ::CtrlCommonParamTbox;
  }
  // @@protoc_insertion_point(field_mutable:CtrlPrivateInformationMessage.common_param)
  return common_param_;
}
inline ::CtrlCommonParamTbox* CtrlPrivateInformationMessage::release_common_param() {
  // @@protoc_insertion_point(field_release:CtrlPrivateInformationMessage.common_param)
  clear_has_common_param();
  ::CtrlCommonParamTbox* temp = common_param_;
  common_param_ = NULL;
  return temp;
}
inline void CtrlPrivateInformationMessage::set_allocated_common_param(::CtrlCommonParamTbox* common_param) {
  delete common_param_;
  common_param_ = common_param;
  if (common_param) {
    set_has_common_param();
  } else {
    clear_has_common_param();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlPrivateInformationMessage.common_param)
}

// optional .CtrlCommonInfo private_info_ctrl_info = 2;
inline bool CtrlPrivateInformationMessage::has_private_info_ctrl_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlPrivateInformationMessage::set_has_private_info_ctrl_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlPrivateInformationMessage::clear_has_private_info_ctrl_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlPrivateInformationMessage::clear_private_info_ctrl_info() {
  if (private_info_ctrl_info_ != NULL) private_info_ctrl_info_->::CtrlCommonInfo::Clear();
  clear_has_private_info_ctrl_info();
}
inline const ::CtrlCommonInfo& CtrlPrivateInformationMessage::private_info_ctrl_info() const {
  // @@protoc_insertion_point(field_get:CtrlPrivateInformationMessage.private_info_ctrl_info)
  return private_info_ctrl_info_ != NULL ? *private_info_ctrl_info_ : *default_instance_->private_info_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlPrivateInformationMessage::mutable_private_info_ctrl_info() {
  set_has_private_info_ctrl_info();
  if (private_info_ctrl_info_ == NULL) {
    private_info_ctrl_info_ = new ::CtrlCommonInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlPrivateInformationMessage.private_info_ctrl_info)
  return private_info_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlPrivateInformationMessage::release_private_info_ctrl_info() {
  // @@protoc_insertion_point(field_release:CtrlPrivateInformationMessage.private_info_ctrl_info)
  clear_has_private_info_ctrl_info();
  ::CtrlCommonInfo* temp = private_info_ctrl_info_;
  private_info_ctrl_info_ = NULL;
  return temp;
}
inline void CtrlPrivateInformationMessage::set_allocated_private_info_ctrl_info(::CtrlCommonInfo* private_info_ctrl_info) {
  delete private_info_ctrl_info_;
  private_info_ctrl_info_ = private_info_ctrl_info;
  if (private_info_ctrl_info) {
    set_has_private_info_ctrl_info();
  } else {
    clear_has_private_info_ctrl_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlPrivateInformationMessage.private_info_ctrl_info)
}

// optional .PrivateInfoStateInfo private_info_state_info = 3;
inline bool CtrlPrivateInformationMessage::has_private_info_state_info() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CtrlPrivateInformationMessage::set_has_private_info_state_info() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CtrlPrivateInformationMessage::clear_has_private_info_state_info() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CtrlPrivateInformationMessage::clear_private_info_state_info() {
  if (private_info_state_info_ != NULL) private_info_state_info_->::PrivateInfoStateInfo::Clear();
  clear_has_private_info_state_info();
}
inline const ::PrivateInfoStateInfo& CtrlPrivateInformationMessage::private_info_state_info() const {
  // @@protoc_insertion_point(field_get:CtrlPrivateInformationMessage.private_info_state_info)
  return private_info_state_info_ != NULL ? *private_info_state_info_ : *default_instance_->private_info_state_info_;
}
inline ::PrivateInfoStateInfo* CtrlPrivateInformationMessage::mutable_private_info_state_info() {
  set_has_private_info_state_info();
  if (private_info_state_info_ == NULL) {
    private_info_state_info_ = new ::PrivateInfoStateInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlPrivateInformationMessage.private_info_state_info)
  return private_info_state_info_;
}
inline ::PrivateInfoStateInfo* CtrlPrivateInformationMessage::release_private_info_state_info() {
  // @@protoc_insertion_point(field_release:CtrlPrivateInformationMessage.private_info_state_info)
  clear_has_private_info_state_info();
  ::PrivateInfoStateInfo* temp = private_info_state_info_;
  private_info_state_info_ = NULL;
  return temp;
}
inline void CtrlPrivateInformationMessage::set_allocated_private_info_state_info(::PrivateInfoStateInfo* private_info_state_info) {
  delete private_info_state_info_;
  private_info_state_info_ = private_info_state_info;
  if (private_info_state_info) {
    set_has_private_info_state_info();
  } else {
    clear_has_private_info_state_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlPrivateInformationMessage.private_info_state_info)
}

// -------------------------------------------------------------------

// PrivateInfoStateInfo

// optional int32 lock_state = 1;
inline bool PrivateInfoStateInfo::has_lock_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PrivateInfoStateInfo::set_has_lock_state() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PrivateInfoStateInfo::clear_has_lock_state() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PrivateInfoStateInfo::clear_lock_state() {
  lock_state_ = 0;
  clear_has_lock_state();
}
inline ::google::protobuf::int32 PrivateInfoStateInfo::lock_state() const {
  // @@protoc_insertion_point(field_get:PrivateInfoStateInfo.lock_state)
  return lock_state_;
}
inline void PrivateInfoStateInfo::set_lock_state(::google::protobuf::int32 value) {
  set_has_lock_state();
  lock_state_ = value;
  // @@protoc_insertion_point(field_set:PrivateInfoStateInfo.lock_state)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ctrl_5fprivate_5finformation_2eproto__INCLUDED
