// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl_engine.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ctrl_engine.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CtrlEngineMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CtrlEngineMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* EngineStateInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  EngineStateInfo_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ctrl_5fengine_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_ctrl_5fengine_2eproto() {
  protobuf_AddDesc_ctrl_5fengine_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ctrl_engine.proto");
  GOOGLE_CHECK(file != NULL);
  CtrlEngineMessage_descriptor_ = file->message_type(0);
  static const int CtrlEngineMessage_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlEngineMessage, common_param_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlEngineMessage, engine_ctrl_info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlEngineMessage, engine_state_info_),
  };
  CtrlEngineMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CtrlEngineMessage_descriptor_,
      CtrlEngineMessage::default_instance_,
      CtrlEngineMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlEngineMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(CtrlEngineMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlEngineMessage, _internal_metadata_),
      -1);
  EngineStateInfo_descriptor_ = file->message_type(1);
  static const int EngineStateInfo_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EngineStateInfo, engine_start_state_),
  };
  EngineStateInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      EngineStateInfo_descriptor_,
      EngineStateInfo::default_instance_,
      EngineStateInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EngineStateInfo, _has_bits_[0]),
      -1,
      -1,
      sizeof(EngineStateInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(EngineStateInfo, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ctrl_5fengine_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CtrlEngineMessage_descriptor_, &CtrlEngineMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      EngineStateInfo_descriptor_, &EngineStateInfo::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ctrl_5fengine_2eproto() {
  delete CtrlEngineMessage::default_instance_;
  delete CtrlEngineMessage_reflection_;
  delete EngineStateInfo::default_instance_;
  delete EngineStateInfo_reflection_;
}

void protobuf_AddDesc_ctrl_5fengine_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ctrl_5fengine_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_ctrl_5fcommon_5fparam_5ftbox_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021ctrl_engine.proto\032\034ctrl_common_param_t"
    "box.proto\"\227\001\n\021CtrlEngineMessage\022*\n\014commo"
    "n_param\030\001 \001(\0132\024.CtrlCommonParamTbox\022)\n\020e"
    "ngine_ctrl_info\030\002 \001(\0132\017.CtrlCommonInfo\022+"
    "\n\021engine_state_info\030\003 \001(\0132\020.EngineStateI"
    "nfo\"-\n\017EngineStateInfo\022\032\n\022engine_start_s"
    "tate\030\001 \001(\005B.\n\034com.mx.server.remote.v2.be"
    "anB\016CtrlEngineBean", 298);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ctrl_engine.proto", &protobuf_RegisterTypes);
  CtrlEngineMessage::default_instance_ = new CtrlEngineMessage();
  EngineStateInfo::default_instance_ = new EngineStateInfo();
  CtrlEngineMessage::default_instance_->InitAsDefaultInstance();
  EngineStateInfo::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ctrl_5fengine_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ctrl_5fengine_2eproto {
  StaticDescriptorInitializer_ctrl_5fengine_2eproto() {
    protobuf_AddDesc_ctrl_5fengine_2eproto();
  }
} static_descriptor_initializer_ctrl_5fengine_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CtrlEngineMessage::kCommonParamFieldNumber;
const int CtrlEngineMessage::kEngineCtrlInfoFieldNumber;
const int CtrlEngineMessage::kEngineStateInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CtrlEngineMessage::CtrlEngineMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CtrlEngineMessage)
}

void CtrlEngineMessage::InitAsDefaultInstance() {
  common_param_ = const_cast< ::CtrlCommonParamTbox*>(&::CtrlCommonParamTbox::default_instance());
  engine_ctrl_info_ = const_cast< ::CtrlCommonInfo*>(&::CtrlCommonInfo::default_instance());
  engine_state_info_ = const_cast< ::EngineStateInfo*>(&::EngineStateInfo::default_instance());
}

CtrlEngineMessage::CtrlEngineMessage(const CtrlEngineMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CtrlEngineMessage)
}

void CtrlEngineMessage::SharedCtor() {
  _cached_size_ = 0;
  common_param_ = NULL;
  engine_ctrl_info_ = NULL;
  engine_state_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CtrlEngineMessage::~CtrlEngineMessage() {
  // @@protoc_insertion_point(destructor:CtrlEngineMessage)
  SharedDtor();
}

void CtrlEngineMessage::SharedDtor() {
  if (this != default_instance_) {
    delete common_param_;
    delete engine_ctrl_info_;
    delete engine_state_info_;
  }
}

void CtrlEngineMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CtrlEngineMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CtrlEngineMessage_descriptor_;
}

const CtrlEngineMessage& CtrlEngineMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ctrl_5fengine_2eproto();
  return *default_instance_;
}

CtrlEngineMessage* CtrlEngineMessage::default_instance_ = NULL;

CtrlEngineMessage* CtrlEngineMessage::New(::google::protobuf::Arena* arena) const {
  CtrlEngineMessage* n = new CtrlEngineMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CtrlEngineMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:CtrlEngineMessage)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_common_param()) {
      if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
    }
    if (has_engine_ctrl_info()) {
      if (engine_ctrl_info_ != NULL) engine_ctrl_info_->::CtrlCommonInfo::Clear();
    }
    if (has_engine_state_info()) {
      if (engine_state_info_ != NULL) engine_state_info_->::EngineStateInfo::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CtrlEngineMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CtrlEngineMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CtrlCommonParamTbox common_param = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_common_param()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_engine_ctrl_info;
        break;
      }

      // optional .CtrlCommonInfo engine_ctrl_info = 2;
      case 2: {
        if (tag == 18) {
         parse_engine_ctrl_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_engine_ctrl_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_engine_state_info;
        break;
      }

      // optional .EngineStateInfo engine_state_info = 3;
      case 3: {
        if (tag == 26) {
         parse_engine_state_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_engine_state_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CtrlEngineMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CtrlEngineMessage)
  return false;
#undef DO_
}

void CtrlEngineMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CtrlEngineMessage)
  // optional .CtrlCommonParamTbox common_param = 1;
  if (has_common_param()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->common_param_, output);
  }

  // optional .CtrlCommonInfo engine_ctrl_info = 2;
  if (has_engine_ctrl_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->engine_ctrl_info_, output);
  }

  // optional .EngineStateInfo engine_state_info = 3;
  if (has_engine_state_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->engine_state_info_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CtrlEngineMessage)
}

::google::protobuf::uint8* CtrlEngineMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CtrlEngineMessage)
  // optional .CtrlCommonParamTbox common_param = 1;
  if (has_common_param()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->common_param_, false, target);
  }

  // optional .CtrlCommonInfo engine_ctrl_info = 2;
  if (has_engine_ctrl_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->engine_ctrl_info_, false, target);
  }

  // optional .EngineStateInfo engine_state_info = 3;
  if (has_engine_state_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->engine_state_info_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CtrlEngineMessage)
  return target;
}

int CtrlEngineMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CtrlEngineMessage)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7u) {
    // optional .CtrlCommonParamTbox common_param = 1;
    if (has_common_param()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->common_param_);
    }

    // optional .CtrlCommonInfo engine_ctrl_info = 2;
    if (has_engine_ctrl_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->engine_ctrl_info_);
    }

    // optional .EngineStateInfo engine_state_info = 3;
    if (has_engine_state_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->engine_state_info_);
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CtrlEngineMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CtrlEngineMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CtrlEngineMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CtrlEngineMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CtrlEngineMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CtrlEngineMessage)
    MergeFrom(*source);
  }
}

void CtrlEngineMessage::MergeFrom(const CtrlEngineMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CtrlEngineMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_common_param()) {
      mutable_common_param()->::CtrlCommonParamTbox::MergeFrom(from.common_param());
    }
    if (from.has_engine_ctrl_info()) {
      mutable_engine_ctrl_info()->::CtrlCommonInfo::MergeFrom(from.engine_ctrl_info());
    }
    if (from.has_engine_state_info()) {
      mutable_engine_state_info()->::EngineStateInfo::MergeFrom(from.engine_state_info());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CtrlEngineMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CtrlEngineMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CtrlEngineMessage::CopyFrom(const CtrlEngineMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CtrlEngineMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CtrlEngineMessage::IsInitialized() const {

  return true;
}

void CtrlEngineMessage::Swap(CtrlEngineMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CtrlEngineMessage::InternalSwap(CtrlEngineMessage* other) {
  std::swap(common_param_, other->common_param_);
  std::swap(engine_ctrl_info_, other->engine_ctrl_info_);
  std::swap(engine_state_info_, other->engine_state_info_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CtrlEngineMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CtrlEngineMessage_descriptor_;
  metadata.reflection = CtrlEngineMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlEngineMessage

// optional .CtrlCommonParamTbox common_param = 1;
bool CtrlEngineMessage::has_common_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CtrlEngineMessage::set_has_common_param() {
  _has_bits_[0] |= 0x00000001u;
}
void CtrlEngineMessage::clear_has_common_param() {
  _has_bits_[0] &= ~0x00000001u;
}
void CtrlEngineMessage::clear_common_param() {
  if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
  clear_has_common_param();
}
const ::CtrlCommonParamTbox& CtrlEngineMessage::common_param() const {
  // @@protoc_insertion_point(field_get:CtrlEngineMessage.common_param)
  return common_param_ != NULL ? *common_param_ : *default_instance_->common_param_;
}
::CtrlCommonParamTbox* CtrlEngineMessage::mutable_common_param() {
  set_has_common_param();
  if (common_param_ == NULL) {
    common_param_ = new ::CtrlCommonParamTbox;
  }
  // @@protoc_insertion_point(field_mutable:CtrlEngineMessage.common_param)
  return common_param_;
}
::CtrlCommonParamTbox* CtrlEngineMessage::release_common_param() {
  // @@protoc_insertion_point(field_release:CtrlEngineMessage.common_param)
  clear_has_common_param();
  ::CtrlCommonParamTbox* temp = common_param_;
  common_param_ = NULL;
  return temp;
}
void CtrlEngineMessage::set_allocated_common_param(::CtrlCommonParamTbox* common_param) {
  delete common_param_;
  common_param_ = common_param;
  if (common_param) {
    set_has_common_param();
  } else {
    clear_has_common_param();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlEngineMessage.common_param)
}

// optional .CtrlCommonInfo engine_ctrl_info = 2;
bool CtrlEngineMessage::has_engine_ctrl_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CtrlEngineMessage::set_has_engine_ctrl_info() {
  _has_bits_[0] |= 0x00000002u;
}
void CtrlEngineMessage::clear_has_engine_ctrl_info() {
  _has_bits_[0] &= ~0x00000002u;
}
void CtrlEngineMessage::clear_engine_ctrl_info() {
  if (engine_ctrl_info_ != NULL) engine_ctrl_info_->::CtrlCommonInfo::Clear();
  clear_has_engine_ctrl_info();
}
const ::CtrlCommonInfo& CtrlEngineMessage::engine_ctrl_info() const {
  // @@protoc_insertion_point(field_get:CtrlEngineMessage.engine_ctrl_info)
  return engine_ctrl_info_ != NULL ? *engine_ctrl_info_ : *default_instance_->engine_ctrl_info_;
}
::CtrlCommonInfo* CtrlEngineMessage::mutable_engine_ctrl_info() {
  set_has_engine_ctrl_info();
  if (engine_ctrl_info_ == NULL) {
    engine_ctrl_info_ = new ::CtrlCommonInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlEngineMessage.engine_ctrl_info)
  return engine_ctrl_info_;
}
::CtrlCommonInfo* CtrlEngineMessage::release_engine_ctrl_info() {
  // @@protoc_insertion_point(field_release:CtrlEngineMessage.engine_ctrl_info)
  clear_has_engine_ctrl_info();
  ::CtrlCommonInfo* temp = engine_ctrl_info_;
  engine_ctrl_info_ = NULL;
  return temp;
}
void CtrlEngineMessage::set_allocated_engine_ctrl_info(::CtrlCommonInfo* engine_ctrl_info) {
  delete engine_ctrl_info_;
  engine_ctrl_info_ = engine_ctrl_info;
  if (engine_ctrl_info) {
    set_has_engine_ctrl_info();
  } else {
    clear_has_engine_ctrl_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlEngineMessage.engine_ctrl_info)
}

// optional .EngineStateInfo engine_state_info = 3;
bool CtrlEngineMessage::has_engine_state_info() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void CtrlEngineMessage::set_has_engine_state_info() {
  _has_bits_[0] |= 0x00000004u;
}
void CtrlEngineMessage::clear_has_engine_state_info() {
  _has_bits_[0] &= ~0x00000004u;
}
void CtrlEngineMessage::clear_engine_state_info() {
  if (engine_state_info_ != NULL) engine_state_info_->::EngineStateInfo::Clear();
  clear_has_engine_state_info();
}
const ::EngineStateInfo& CtrlEngineMessage::engine_state_info() const {
  // @@protoc_insertion_point(field_get:CtrlEngineMessage.engine_state_info)
  return engine_state_info_ != NULL ? *engine_state_info_ : *default_instance_->engine_state_info_;
}
::EngineStateInfo* CtrlEngineMessage::mutable_engine_state_info() {
  set_has_engine_state_info();
  if (engine_state_info_ == NULL) {
    engine_state_info_ = new ::EngineStateInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlEngineMessage.engine_state_info)
  return engine_state_info_;
}
::EngineStateInfo* CtrlEngineMessage::release_engine_state_info() {
  // @@protoc_insertion_point(field_release:CtrlEngineMessage.engine_state_info)
  clear_has_engine_state_info();
  ::EngineStateInfo* temp = engine_state_info_;
  engine_state_info_ = NULL;
  return temp;
}
void CtrlEngineMessage::set_allocated_engine_state_info(::EngineStateInfo* engine_state_info) {
  delete engine_state_info_;
  engine_state_info_ = engine_state_info;
  if (engine_state_info) {
    set_has_engine_state_info();
  } else {
    clear_has_engine_state_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlEngineMessage.engine_state_info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EngineStateInfo::kEngineStartStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EngineStateInfo::EngineStateInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:EngineStateInfo)
}

void EngineStateInfo::InitAsDefaultInstance() {
}

EngineStateInfo::EngineStateInfo(const EngineStateInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:EngineStateInfo)
}

void EngineStateInfo::SharedCtor() {
  _cached_size_ = 0;
  engine_start_state_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

EngineStateInfo::~EngineStateInfo() {
  // @@protoc_insertion_point(destructor:EngineStateInfo)
  SharedDtor();
}

void EngineStateInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void EngineStateInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EngineStateInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return EngineStateInfo_descriptor_;
}

const EngineStateInfo& EngineStateInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ctrl_5fengine_2eproto();
  return *default_instance_;
}

EngineStateInfo* EngineStateInfo::default_instance_ = NULL;

EngineStateInfo* EngineStateInfo::New(::google::protobuf::Arena* arena) const {
  EngineStateInfo* n = new EngineStateInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void EngineStateInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:EngineStateInfo)
  engine_start_state_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool EngineStateInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:EngineStateInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 engine_start_state = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &engine_start_state_)));
          set_has_engine_start_state();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:EngineStateInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:EngineStateInfo)
  return false;
#undef DO_
}

void EngineStateInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:EngineStateInfo)
  // optional int32 engine_start_state = 1;
  if (has_engine_start_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->engine_start_state(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:EngineStateInfo)
}

::google::protobuf::uint8* EngineStateInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:EngineStateInfo)
  // optional int32 engine_start_state = 1;
  if (has_engine_start_state()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->engine_start_state(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:EngineStateInfo)
  return target;
}

int EngineStateInfo::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:EngineStateInfo)
  int total_size = 0;

  // optional int32 engine_start_state = 1;
  if (has_engine_start_state()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->engine_start_state());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EngineStateInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:EngineStateInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const EngineStateInfo* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const EngineStateInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:EngineStateInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:EngineStateInfo)
    MergeFrom(*source);
  }
}

void EngineStateInfo::MergeFrom(const EngineStateInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:EngineStateInfo)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_engine_start_state()) {
      set_engine_start_state(from.engine_start_state());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void EngineStateInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:EngineStateInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EngineStateInfo::CopyFrom(const EngineStateInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:EngineStateInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EngineStateInfo::IsInitialized() const {

  return true;
}

void EngineStateInfo::Swap(EngineStateInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EngineStateInfo::InternalSwap(EngineStateInfo* other) {
  std::swap(engine_start_state_, other->engine_start_state_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EngineStateInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = EngineStateInfo_descriptor_;
  metadata.reflection = EngineStateInfo_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// EngineStateInfo

// optional int32 engine_start_state = 1;
bool EngineStateInfo::has_engine_start_state() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void EngineStateInfo::set_has_engine_start_state() {
  _has_bits_[0] |= 0x00000001u;
}
void EngineStateInfo::clear_has_engine_start_state() {
  _has_bits_[0] &= ~0x00000001u;
}
void EngineStateInfo::clear_engine_start_state() {
  engine_start_state_ = 0;
  clear_has_engine_start_state();
}
 ::google::protobuf::int32 EngineStateInfo::engine_start_state() const {
  // @@protoc_insertion_point(field_get:EngineStateInfo.engine_start_state)
  return engine_start_state_;
}
 void EngineStateInfo::set_engine_start_state(::google::protobuf::int32 value) {
  set_has_engine_start_state();
  engine_start_state_ = value;
  // @@protoc_insertion_point(field_set:EngineStateInfo.engine_start_state)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
