// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl_chair.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ctrl_chair.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* CtrlChairMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CtrlChairMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ctrl_5fchair_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_ctrl_5fchair_2eproto() {
  protobuf_AddDesc_ctrl_5fchair_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ctrl_chair.proto");
  GOOGLE_CHECK(file != NULL);
  CtrlChairMessage_descriptor_ = file->message_type(0);
  static const int CtrlChairMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlChairMessage, common_param_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlChairMessage, chair_ctrl_info_),
  };
  CtrlChairMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CtrlChairMessage_descriptor_,
      CtrlChairMessage::default_instance_,
      CtrlChairMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlChairMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(CtrlChairMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CtrlChairMessage, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ctrl_5fchair_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CtrlChairMessage_descriptor_, &CtrlChairMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ctrl_5fchair_2eproto() {
  delete CtrlChairMessage::default_instance_;
  delete CtrlChairMessage_reflection_;
}

void protobuf_AddDesc_ctrl_5fchair_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ctrl_5fchair_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_ctrl_5fcommon_5fparam_5ftbox_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ctrl_chair.proto\032\034ctrl_common_param_tb"
    "ox.proto\"h\n\020CtrlChairMessage\022*\n\014common_p"
    "aram\030\001 \001(\0132\024.CtrlCommonParamTbox\022(\n\017chai"
    "r_ctrl_info\030\002 \001(\0132\017.CtrlCommonInfoB-\n\034co"
    "m.mx.server.remote.v2.beanB\rCtrlChairBea"
    "n", 201);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ctrl_chair.proto", &protobuf_RegisterTypes);
  CtrlChairMessage::default_instance_ = new CtrlChairMessage();
  CtrlChairMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ctrl_5fchair_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ctrl_5fchair_2eproto {
  StaticDescriptorInitializer_ctrl_5fchair_2eproto() {
    protobuf_AddDesc_ctrl_5fchair_2eproto();
  }
} static_descriptor_initializer_ctrl_5fchair_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CtrlChairMessage::kCommonParamFieldNumber;
const int CtrlChairMessage::kChairCtrlInfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CtrlChairMessage::CtrlChairMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CtrlChairMessage)
}

void CtrlChairMessage::InitAsDefaultInstance() {
  common_param_ = const_cast< ::CtrlCommonParamTbox*>(&::CtrlCommonParamTbox::default_instance());
  chair_ctrl_info_ = const_cast< ::CtrlCommonInfo*>(&::CtrlCommonInfo::default_instance());
}

CtrlChairMessage::CtrlChairMessage(const CtrlChairMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CtrlChairMessage)
}

void CtrlChairMessage::SharedCtor() {
  _cached_size_ = 0;
  common_param_ = NULL;
  chair_ctrl_info_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CtrlChairMessage::~CtrlChairMessage() {
  // @@protoc_insertion_point(destructor:CtrlChairMessage)
  SharedDtor();
}

void CtrlChairMessage::SharedDtor() {
  if (this != default_instance_) {
    delete common_param_;
    delete chair_ctrl_info_;
  }
}

void CtrlChairMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CtrlChairMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CtrlChairMessage_descriptor_;
}

const CtrlChairMessage& CtrlChairMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ctrl_5fchair_2eproto();
  return *default_instance_;
}

CtrlChairMessage* CtrlChairMessage::default_instance_ = NULL;

CtrlChairMessage* CtrlChairMessage::New(::google::protobuf::Arena* arena) const {
  CtrlChairMessage* n = new CtrlChairMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CtrlChairMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:CtrlChairMessage)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_common_param()) {
      if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
    }
    if (has_chair_ctrl_info()) {
      if (chair_ctrl_info_ != NULL) chair_ctrl_info_->::CtrlCommonInfo::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CtrlChairMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CtrlChairMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CtrlCommonParamTbox common_param = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_common_param()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_chair_ctrl_info;
        break;
      }

      // optional .CtrlCommonInfo chair_ctrl_info = 2;
      case 2: {
        if (tag == 18) {
         parse_chair_ctrl_info:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_chair_ctrl_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CtrlChairMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CtrlChairMessage)
  return false;
#undef DO_
}

void CtrlChairMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CtrlChairMessage)
  // optional .CtrlCommonParamTbox common_param = 1;
  if (has_common_param()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->common_param_, output);
  }

  // optional .CtrlCommonInfo chair_ctrl_info = 2;
  if (has_chair_ctrl_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->chair_ctrl_info_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CtrlChairMessage)
}

::google::protobuf::uint8* CtrlChairMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CtrlChairMessage)
  // optional .CtrlCommonParamTbox common_param = 1;
  if (has_common_param()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->common_param_, false, target);
  }

  // optional .CtrlCommonInfo chair_ctrl_info = 2;
  if (has_chair_ctrl_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->chair_ctrl_info_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CtrlChairMessage)
  return target;
}

int CtrlChairMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:CtrlChairMessage)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3u) {
    // optional .CtrlCommonParamTbox common_param = 1;
    if (has_common_param()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->common_param_);
    }

    // optional .CtrlCommonInfo chair_ctrl_info = 2;
    if (has_chair_ctrl_info()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->chair_ctrl_info_);
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CtrlChairMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CtrlChairMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const CtrlChairMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CtrlChairMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CtrlChairMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CtrlChairMessage)
    MergeFrom(*source);
  }
}

void CtrlChairMessage::MergeFrom(const CtrlChairMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CtrlChairMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_common_param()) {
      mutable_common_param()->::CtrlCommonParamTbox::MergeFrom(from.common_param());
    }
    if (from.has_chair_ctrl_info()) {
      mutable_chair_ctrl_info()->::CtrlCommonInfo::MergeFrom(from.chair_ctrl_info());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CtrlChairMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CtrlChairMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CtrlChairMessage::CopyFrom(const CtrlChairMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CtrlChairMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CtrlChairMessage::IsInitialized() const {

  return true;
}

void CtrlChairMessage::Swap(CtrlChairMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CtrlChairMessage::InternalSwap(CtrlChairMessage* other) {
  std::swap(common_param_, other->common_param_);
  std::swap(chair_ctrl_info_, other->chair_ctrl_info_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CtrlChairMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CtrlChairMessage_descriptor_;
  metadata.reflection = CtrlChairMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlChairMessage

// optional .CtrlCommonParamTbox common_param = 1;
bool CtrlChairMessage::has_common_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CtrlChairMessage::set_has_common_param() {
  _has_bits_[0] |= 0x00000001u;
}
void CtrlChairMessage::clear_has_common_param() {
  _has_bits_[0] &= ~0x00000001u;
}
void CtrlChairMessage::clear_common_param() {
  if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
  clear_has_common_param();
}
const ::CtrlCommonParamTbox& CtrlChairMessage::common_param() const {
  // @@protoc_insertion_point(field_get:CtrlChairMessage.common_param)
  return common_param_ != NULL ? *common_param_ : *default_instance_->common_param_;
}
::CtrlCommonParamTbox* CtrlChairMessage::mutable_common_param() {
  set_has_common_param();
  if (common_param_ == NULL) {
    common_param_ = new ::CtrlCommonParamTbox;
  }
  // @@protoc_insertion_point(field_mutable:CtrlChairMessage.common_param)
  return common_param_;
}
::CtrlCommonParamTbox* CtrlChairMessage::release_common_param() {
  // @@protoc_insertion_point(field_release:CtrlChairMessage.common_param)
  clear_has_common_param();
  ::CtrlCommonParamTbox* temp = common_param_;
  common_param_ = NULL;
  return temp;
}
void CtrlChairMessage::set_allocated_common_param(::CtrlCommonParamTbox* common_param) {
  delete common_param_;
  common_param_ = common_param;
  if (common_param) {
    set_has_common_param();
  } else {
    clear_has_common_param();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlChairMessage.common_param)
}

// optional .CtrlCommonInfo chair_ctrl_info = 2;
bool CtrlChairMessage::has_chair_ctrl_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void CtrlChairMessage::set_has_chair_ctrl_info() {
  _has_bits_[0] |= 0x00000002u;
}
void CtrlChairMessage::clear_has_chair_ctrl_info() {
  _has_bits_[0] &= ~0x00000002u;
}
void CtrlChairMessage::clear_chair_ctrl_info() {
  if (chair_ctrl_info_ != NULL) chair_ctrl_info_->::CtrlCommonInfo::Clear();
  clear_has_chair_ctrl_info();
}
const ::CtrlCommonInfo& CtrlChairMessage::chair_ctrl_info() const {
  // @@protoc_insertion_point(field_get:CtrlChairMessage.chair_ctrl_info)
  return chair_ctrl_info_ != NULL ? *chair_ctrl_info_ : *default_instance_->chair_ctrl_info_;
}
::CtrlCommonInfo* CtrlChairMessage::mutable_chair_ctrl_info() {
  set_has_chair_ctrl_info();
  if (chair_ctrl_info_ == NULL) {
    chair_ctrl_info_ = new ::CtrlCommonInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlChairMessage.chair_ctrl_info)
  return chair_ctrl_info_;
}
::CtrlCommonInfo* CtrlChairMessage::release_chair_ctrl_info() {
  // @@protoc_insertion_point(field_release:CtrlChairMessage.chair_ctrl_info)
  clear_has_chair_ctrl_info();
  ::CtrlCommonInfo* temp = chair_ctrl_info_;
  chair_ctrl_info_ = NULL;
  return temp;
}
void CtrlChairMessage::set_allocated_chair_ctrl_info(::CtrlCommonInfo* chair_ctrl_info) {
  delete chair_ctrl_info_;
  chair_ctrl_info_ = chair_ctrl_info;
  if (chair_ctrl_info) {
    set_has_chair_ctrl_info();
  } else {
    clear_has_chair_ctrl_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlChairMessage.chair_ctrl_info)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
