// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ctrl_doors.proto

#ifndef PROTOBUF_ctrl_5fdoors_2eproto__INCLUDED
#define PROTOBUF_ctrl_5fdoors_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "ctrl_common_param_tbox.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ctrl_5fdoors_2eproto();
void protobuf_AssignDesc_ctrl_5fdoors_2eproto();
void protobuf_ShutdownFile_ctrl_5fdoors_2eproto();

class CtrlDoorsMessage;
class DoorsStateInfo;

// ===================================================================

class CtrlDoorsMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CtrlDoorsMessage) */ {
 public:
  CtrlDoorsMessage();
  virtual ~CtrlDoorsMessage();

  CtrlDoorsMessage(const CtrlDoorsMessage& from);

  inline CtrlDoorsMessage& operator=(const CtrlDoorsMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CtrlDoorsMessage& default_instance();

  void Swap(CtrlDoorsMessage* other);

  // implements Message ----------------------------------------------

  inline CtrlDoorsMessage* New() const { return New(NULL); }

  CtrlDoorsMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CtrlDoorsMessage& from);
  void MergeFrom(const CtrlDoorsMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(CtrlDoorsMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CtrlCommonParamTbox common_param = 1;
  bool has_common_param() const;
  void clear_common_param();
  static const int kCommonParamFieldNumber = 1;
  const ::CtrlCommonParamTbox& common_param() const;
  ::CtrlCommonParamTbox* mutable_common_param();
  ::CtrlCommonParamTbox* release_common_param();
  void set_allocated_common_param(::CtrlCommonParamTbox* common_param);

  // optional .CtrlCommonInfo doors_ctrl_info = 2;
  bool has_doors_ctrl_info() const;
  void clear_doors_ctrl_info();
  static const int kDoorsCtrlInfoFieldNumber = 2;
  const ::CtrlCommonInfo& doors_ctrl_info() const;
  ::CtrlCommonInfo* mutable_doors_ctrl_info();
  ::CtrlCommonInfo* release_doors_ctrl_info();
  void set_allocated_doors_ctrl_info(::CtrlCommonInfo* doors_ctrl_info);

  // optional .DoorsStateInfo doors_state_info = 4;
  bool has_doors_state_info() const;
  void clear_doors_state_info();
  static const int kDoorsStateInfoFieldNumber = 4;
  const ::DoorsStateInfo& doors_state_info() const;
  ::DoorsStateInfo* mutable_doors_state_info();
  ::DoorsStateInfo* release_doors_state_info();
  void set_allocated_doors_state_info(::DoorsStateInfo* doors_state_info);

  // @@protoc_insertion_point(class_scope:CtrlDoorsMessage)
 private:
  inline void set_has_common_param();
  inline void clear_has_common_param();
  inline void set_has_doors_ctrl_info();
  inline void clear_has_doors_ctrl_info();
  inline void set_has_doors_state_info();
  inline void clear_has_doors_state_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::CtrlCommonParamTbox* common_param_;
  ::CtrlCommonInfo* doors_ctrl_info_;
  ::DoorsStateInfo* doors_state_info_;
  friend void  protobuf_AddDesc_ctrl_5fdoors_2eproto();
  friend void protobuf_AssignDesc_ctrl_5fdoors_2eproto();
  friend void protobuf_ShutdownFile_ctrl_5fdoors_2eproto();

  void InitAsDefaultInstance();
  static CtrlDoorsMessage* default_instance_;
};
// -------------------------------------------------------------------

class DoorsStateInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DoorsStateInfo) */ {
 public:
  DoorsStateInfo();
  virtual ~DoorsStateInfo();

  DoorsStateInfo(const DoorsStateInfo& from);

  inline DoorsStateInfo& operator=(const DoorsStateInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DoorsStateInfo& default_instance();

  void Swap(DoorsStateInfo* other);

  // implements Message ----------------------------------------------

  inline DoorsStateInfo* New() const { return New(NULL); }

  DoorsStateInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DoorsStateInfo& from);
  void MergeFrom(const DoorsStateInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DoorsStateInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed64 lock_on_off = 1;
  bool has_lock_on_off() const;
  void clear_lock_on_off();
  static const int kLockOnOffFieldNumber = 1;
  ::google::protobuf::uint64 lock_on_off() const;
  void set_lock_on_off(::google::protobuf::uint64 value);

  // optional fixed64 lock_state_exception = 2;
  bool has_lock_state_exception() const;
  void clear_lock_state_exception();
  static const int kLockStateExceptionFieldNumber = 2;
  ::google::protobuf::uint64 lock_state_exception() const;
  void set_lock_state_exception(::google::protobuf::uint64 value);

  // optional fixed64 door_on_off = 4;
  bool has_door_on_off() const;
  void clear_door_on_off();
  static const int kDoorOnOffFieldNumber = 4;
  ::google::protobuf::uint64 door_on_off() const;
  void set_door_on_off(::google::protobuf::uint64 value);

  // optional fixed64 door_state_exception = 6;
  bool has_door_state_exception() const;
  void clear_door_state_exception();
  static const int kDoorStateExceptionFieldNumber = 6;
  ::google::protobuf::uint64 door_state_exception() const;
  void set_door_state_exception(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:DoorsStateInfo)
 private:
  inline void set_has_lock_on_off();
  inline void clear_has_lock_on_off();
  inline void set_has_lock_state_exception();
  inline void clear_has_lock_state_exception();
  inline void set_has_door_on_off();
  inline void clear_has_door_on_off();
  inline void set_has_door_state_exception();
  inline void clear_has_door_state_exception();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 lock_on_off_;
  ::google::protobuf::uint64 lock_state_exception_;
  ::google::protobuf::uint64 door_on_off_;
  ::google::protobuf::uint64 door_state_exception_;
  friend void  protobuf_AddDesc_ctrl_5fdoors_2eproto();
  friend void protobuf_AssignDesc_ctrl_5fdoors_2eproto();
  friend void protobuf_ShutdownFile_ctrl_5fdoors_2eproto();

  void InitAsDefaultInstance();
  static DoorsStateInfo* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CtrlDoorsMessage

// optional .CtrlCommonParamTbox common_param = 1;
inline bool CtrlDoorsMessage::has_common_param() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CtrlDoorsMessage::set_has_common_param() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CtrlDoorsMessage::clear_has_common_param() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CtrlDoorsMessage::clear_common_param() {
  if (common_param_ != NULL) common_param_->::CtrlCommonParamTbox::Clear();
  clear_has_common_param();
}
inline const ::CtrlCommonParamTbox& CtrlDoorsMessage::common_param() const {
  // @@protoc_insertion_point(field_get:CtrlDoorsMessage.common_param)
  return common_param_ != NULL ? *common_param_ : *default_instance_->common_param_;
}
inline ::CtrlCommonParamTbox* CtrlDoorsMessage::mutable_common_param() {
  set_has_common_param();
  if (common_param_ == NULL) {
    common_param_ = new ::CtrlCommonParamTbox;
  }
  // @@protoc_insertion_point(field_mutable:CtrlDoorsMessage.common_param)
  return common_param_;
}
inline ::CtrlCommonParamTbox* CtrlDoorsMessage::release_common_param() {
  // @@protoc_insertion_point(field_release:CtrlDoorsMessage.common_param)
  clear_has_common_param();
  ::CtrlCommonParamTbox* temp = common_param_;
  common_param_ = NULL;
  return temp;
}
inline void CtrlDoorsMessage::set_allocated_common_param(::CtrlCommonParamTbox* common_param) {
  delete common_param_;
  common_param_ = common_param;
  if (common_param) {
    set_has_common_param();
  } else {
    clear_has_common_param();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlDoorsMessage.common_param)
}

// optional .CtrlCommonInfo doors_ctrl_info = 2;
inline bool CtrlDoorsMessage::has_doors_ctrl_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CtrlDoorsMessage::set_has_doors_ctrl_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CtrlDoorsMessage::clear_has_doors_ctrl_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CtrlDoorsMessage::clear_doors_ctrl_info() {
  if (doors_ctrl_info_ != NULL) doors_ctrl_info_->::CtrlCommonInfo::Clear();
  clear_has_doors_ctrl_info();
}
inline const ::CtrlCommonInfo& CtrlDoorsMessage::doors_ctrl_info() const {
  // @@protoc_insertion_point(field_get:CtrlDoorsMessage.doors_ctrl_info)
  return doors_ctrl_info_ != NULL ? *doors_ctrl_info_ : *default_instance_->doors_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlDoorsMessage::mutable_doors_ctrl_info() {
  set_has_doors_ctrl_info();
  if (doors_ctrl_info_ == NULL) {
    doors_ctrl_info_ = new ::CtrlCommonInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlDoorsMessage.doors_ctrl_info)
  return doors_ctrl_info_;
}
inline ::CtrlCommonInfo* CtrlDoorsMessage::release_doors_ctrl_info() {
  // @@protoc_insertion_point(field_release:CtrlDoorsMessage.doors_ctrl_info)
  clear_has_doors_ctrl_info();
  ::CtrlCommonInfo* temp = doors_ctrl_info_;
  doors_ctrl_info_ = NULL;
  return temp;
}
inline void CtrlDoorsMessage::set_allocated_doors_ctrl_info(::CtrlCommonInfo* doors_ctrl_info) {
  delete doors_ctrl_info_;
  doors_ctrl_info_ = doors_ctrl_info;
  if (doors_ctrl_info) {
    set_has_doors_ctrl_info();
  } else {
    clear_has_doors_ctrl_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlDoorsMessage.doors_ctrl_info)
}

// optional .DoorsStateInfo doors_state_info = 4;
inline bool CtrlDoorsMessage::has_doors_state_info() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CtrlDoorsMessage::set_has_doors_state_info() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CtrlDoorsMessage::clear_has_doors_state_info() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CtrlDoorsMessage::clear_doors_state_info() {
  if (doors_state_info_ != NULL) doors_state_info_->::DoorsStateInfo::Clear();
  clear_has_doors_state_info();
}
inline const ::DoorsStateInfo& CtrlDoorsMessage::doors_state_info() const {
  // @@protoc_insertion_point(field_get:CtrlDoorsMessage.doors_state_info)
  return doors_state_info_ != NULL ? *doors_state_info_ : *default_instance_->doors_state_info_;
}
inline ::DoorsStateInfo* CtrlDoorsMessage::mutable_doors_state_info() {
  set_has_doors_state_info();
  if (doors_state_info_ == NULL) {
    doors_state_info_ = new ::DoorsStateInfo;
  }
  // @@protoc_insertion_point(field_mutable:CtrlDoorsMessage.doors_state_info)
  return doors_state_info_;
}
inline ::DoorsStateInfo* CtrlDoorsMessage::release_doors_state_info() {
  // @@protoc_insertion_point(field_release:CtrlDoorsMessage.doors_state_info)
  clear_has_doors_state_info();
  ::DoorsStateInfo* temp = doors_state_info_;
  doors_state_info_ = NULL;
  return temp;
}
inline void CtrlDoorsMessage::set_allocated_doors_state_info(::DoorsStateInfo* doors_state_info) {
  delete doors_state_info_;
  doors_state_info_ = doors_state_info;
  if (doors_state_info) {
    set_has_doors_state_info();
  } else {
    clear_has_doors_state_info();
  }
  // @@protoc_insertion_point(field_set_allocated:CtrlDoorsMessage.doors_state_info)
}

// -------------------------------------------------------------------

// DoorsStateInfo

// optional fixed64 lock_on_off = 1;
inline bool DoorsStateInfo::has_lock_on_off() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DoorsStateInfo::set_has_lock_on_off() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DoorsStateInfo::clear_has_lock_on_off() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DoorsStateInfo::clear_lock_on_off() {
  lock_on_off_ = GOOGLE_ULONGLONG(0);
  clear_has_lock_on_off();
}
inline ::google::protobuf::uint64 DoorsStateInfo::lock_on_off() const {
  // @@protoc_insertion_point(field_get:DoorsStateInfo.lock_on_off)
  return lock_on_off_;
}
inline void DoorsStateInfo::set_lock_on_off(::google::protobuf::uint64 value) {
  set_has_lock_on_off();
  lock_on_off_ = value;
  // @@protoc_insertion_point(field_set:DoorsStateInfo.lock_on_off)
}

// optional fixed64 lock_state_exception = 2;
inline bool DoorsStateInfo::has_lock_state_exception() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DoorsStateInfo::set_has_lock_state_exception() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DoorsStateInfo::clear_has_lock_state_exception() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DoorsStateInfo::clear_lock_state_exception() {
  lock_state_exception_ = GOOGLE_ULONGLONG(0);
  clear_has_lock_state_exception();
}
inline ::google::protobuf::uint64 DoorsStateInfo::lock_state_exception() const {
  // @@protoc_insertion_point(field_get:DoorsStateInfo.lock_state_exception)
  return lock_state_exception_;
}
inline void DoorsStateInfo::set_lock_state_exception(::google::protobuf::uint64 value) {
  set_has_lock_state_exception();
  lock_state_exception_ = value;
  // @@protoc_insertion_point(field_set:DoorsStateInfo.lock_state_exception)
}

// optional fixed64 door_on_off = 4;
inline bool DoorsStateInfo::has_door_on_off() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DoorsStateInfo::set_has_door_on_off() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DoorsStateInfo::clear_has_door_on_off() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DoorsStateInfo::clear_door_on_off() {
  door_on_off_ = GOOGLE_ULONGLONG(0);
  clear_has_door_on_off();
}
inline ::google::protobuf::uint64 DoorsStateInfo::door_on_off() const {
  // @@protoc_insertion_point(field_get:DoorsStateInfo.door_on_off)
  return door_on_off_;
}
inline void DoorsStateInfo::set_door_on_off(::google::protobuf::uint64 value) {
  set_has_door_on_off();
  door_on_off_ = value;
  // @@protoc_insertion_point(field_set:DoorsStateInfo.door_on_off)
}

// optional fixed64 door_state_exception = 6;
inline bool DoorsStateInfo::has_door_state_exception() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DoorsStateInfo::set_has_door_state_exception() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DoorsStateInfo::clear_has_door_state_exception() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DoorsStateInfo::clear_door_state_exception() {
  door_state_exception_ = GOOGLE_ULONGLONG(0);
  clear_has_door_state_exception();
}
inline ::google::protobuf::uint64 DoorsStateInfo::door_state_exception() const {
  // @@protoc_insertion_point(field_get:DoorsStateInfo.door_state_exception)
  return door_state_exception_;
}
inline void DoorsStateInfo::set_door_state_exception(::google::protobuf::uint64 value) {
  set_has_door_state_exception();
  door_state_exception_ = value;
  // @@protoc_insertion_point(field_set:DoorsStateInfo.door_state_exception)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ctrl_5fdoors_2eproto__INCLUDED
