// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device_upload_common.proto

#ifndef PROTOBUF_device_5fupload_5fcommon_2eproto__INCLUDED
#define PROTOBUF_device_5fupload_5fcommon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_device_5fupload_5fcommon_2eproto();
void protobuf_AssignDesc_device_5fupload_5fcommon_2eproto();
void protobuf_ShutdownFile_device_5fupload_5fcommon_2eproto();

class DeviceUploadCommonMessage;

// ===================================================================

class DeviceUploadCommonMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DeviceUploadCommonMessage) */ {
 public:
  DeviceUploadCommonMessage();
  virtual ~DeviceUploadCommonMessage();

  DeviceUploadCommonMessage(const DeviceUploadCommonMessage& from);

  inline DeviceUploadCommonMessage& operator=(const DeviceUploadCommonMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DeviceUploadCommonMessage& default_instance();

  void Swap(DeviceUploadCommonMessage* other);

  // implements Message ----------------------------------------------

  inline DeviceUploadCommonMessage* New() const { return New(NULL); }

  DeviceUploadCommonMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DeviceUploadCommonMessage& from);
  void MergeFrom(const DeviceUploadCommonMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeviceUploadCommonMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed64 request_id = 1;
  bool has_request_id() const;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 1;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // optional int32 upload_category = 2;
  bool has_upload_category() const;
  void clear_upload_category();
  static const int kUploadCategoryFieldNumber = 2;
  ::google::protobuf::int32 upload_category() const;
  void set_upload_category(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DeviceUploadCommonMessage)
 private:
  inline void set_has_request_id();
  inline void clear_has_request_id();
  inline void set_has_upload_category();
  inline void clear_has_upload_category();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::int32 upload_category_;
  friend void  protobuf_AddDesc_device_5fupload_5fcommon_2eproto();
  friend void protobuf_AssignDesc_device_5fupload_5fcommon_2eproto();
  friend void protobuf_ShutdownFile_device_5fupload_5fcommon_2eproto();

  void InitAsDefaultInstance();
  static DeviceUploadCommonMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// DeviceUploadCommonMessage

// optional fixed64 request_id = 1;
inline bool DeviceUploadCommonMessage::has_request_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DeviceUploadCommonMessage::set_has_request_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DeviceUploadCommonMessage::clear_has_request_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DeviceUploadCommonMessage::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
  clear_has_request_id();
}
inline ::google::protobuf::uint64 DeviceUploadCommonMessage::request_id() const {
  // @@protoc_insertion_point(field_get:DeviceUploadCommonMessage.request_id)
  return request_id_;
}
inline void DeviceUploadCommonMessage::set_request_id(::google::protobuf::uint64 value) {
  set_has_request_id();
  request_id_ = value;
  // @@protoc_insertion_point(field_set:DeviceUploadCommonMessage.request_id)
}

// optional int32 upload_category = 2;
inline bool DeviceUploadCommonMessage::has_upload_category() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DeviceUploadCommonMessage::set_has_upload_category() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DeviceUploadCommonMessage::clear_has_upload_category() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DeviceUploadCommonMessage::clear_upload_category() {
  upload_category_ = 0;
  clear_has_upload_category();
}
inline ::google::protobuf::int32 DeviceUploadCommonMessage::upload_category() const {
  // @@protoc_insertion_point(field_get:DeviceUploadCommonMessage.upload_category)
  return upload_category_;
}
inline void DeviceUploadCommonMessage::set_upload_category(::google::protobuf::int32 value) {
  set_has_upload_category();
  upload_category_ = value;
  // @@protoc_insertion_point(field_set:DeviceUploadCommonMessage.upload_category)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_device_5fupload_5fcommon_2eproto__INCLUDED
