// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: state_lighting.proto

#ifndef PROTOBUF_state_5flighting_2eproto__INCLUDED
#define PROTOBUF_state_5flighting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2007000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_state_5flighting_2eproto();
void protobuf_AssignDesc_state_5flighting_2eproto();
void protobuf_ShutdownFile_state_5flighting_2eproto();

class StateLightingMessage;

// ===================================================================

class StateLightingMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StateLightingMessage) */ {
 public:
  StateLightingMessage();
  virtual ~StateLightingMessage();

  StateLightingMessage(const StateLightingMessage& from);

  inline StateLightingMessage& operator=(const StateLightingMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const StateLightingMessage& default_instance();

  void Swap(StateLightingMessage* other);

  // implements Message ----------------------------------------------

  inline StateLightingMessage* New() const { return New(NULL); }

  StateLightingMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const StateLightingMessage& from);
  void MergeFrom(const StateLightingMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(StateLightingMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 low_beam = 1;
  bool has_low_beam() const;
  void clear_low_beam();
  static const int kLowBeamFieldNumber = 1;
  ::google::protobuf::int32 low_beam() const;
  void set_low_beam(::google::protobuf::int32 value);

  // optional int32 high_beam = 2;
  bool has_high_beam() const;
  void clear_high_beam();
  static const int kHighBeamFieldNumber = 2;
  ::google::protobuf::int32 high_beam() const;
  void set_high_beam(::google::protobuf::int32 value);

  // optional int32 left_cornering_lamp = 4;
  bool has_left_cornering_lamp() const;
  void clear_left_cornering_lamp();
  static const int kLeftCorneringLampFieldNumber = 4;
  ::google::protobuf::int32 left_cornering_lamp() const;
  void set_left_cornering_lamp(::google::protobuf::int32 value);

  // optional int32 right_cornering_lamp = 6;
  bool has_right_cornering_lamp() const;
  void clear_right_cornering_lamp();
  static const int kRightCorneringLampFieldNumber = 6;
  ::google::protobuf::int32 right_cornering_lamp() const;
  void set_right_cornering_lamp(::google::protobuf::int32 value);

  // optional int32 clearance_light = 8;
  bool has_clearance_light() const;
  void clear_clearance_light();
  static const int kClearanceLightFieldNumber = 8;
  ::google::protobuf::int32 clearance_light() const;
  void set_clearance_light(::google::protobuf::int32 value);

  // optional int32 fog_light = 10;
  bool has_fog_light() const;
  void clear_fog_light();
  static const int kFogLightFieldNumber = 10;
  ::google::protobuf::int32 fog_light() const;
  void set_fog_light(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StateLightingMessage)
 private:
  inline void set_has_low_beam();
  inline void clear_has_low_beam();
  inline void set_has_high_beam();
  inline void clear_has_high_beam();
  inline void set_has_left_cornering_lamp();
  inline void clear_has_left_cornering_lamp();
  inline void set_has_right_cornering_lamp();
  inline void clear_has_right_cornering_lamp();
  inline void set_has_clearance_light();
  inline void clear_has_clearance_light();
  inline void set_has_fog_light();
  inline void clear_has_fog_light();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 low_beam_;
  ::google::protobuf::int32 high_beam_;
  ::google::protobuf::int32 left_cornering_lamp_;
  ::google::protobuf::int32 right_cornering_lamp_;
  ::google::protobuf::int32 clearance_light_;
  ::google::protobuf::int32 fog_light_;
  friend void  protobuf_AddDesc_state_5flighting_2eproto();
  friend void protobuf_AssignDesc_state_5flighting_2eproto();
  friend void protobuf_ShutdownFile_state_5flighting_2eproto();

  void InitAsDefaultInstance();
  static StateLightingMessage* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// StateLightingMessage

// optional int32 low_beam = 1;
inline bool StateLightingMessage::has_low_beam() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void StateLightingMessage::set_has_low_beam() {
  _has_bits_[0] |= 0x00000001u;
}
inline void StateLightingMessage::clear_has_low_beam() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void StateLightingMessage::clear_low_beam() {
  low_beam_ = 0;
  clear_has_low_beam();
}
inline ::google::protobuf::int32 StateLightingMessage::low_beam() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.low_beam)
  return low_beam_;
}
inline void StateLightingMessage::set_low_beam(::google::protobuf::int32 value) {
  set_has_low_beam();
  low_beam_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.low_beam)
}

// optional int32 high_beam = 2;
inline bool StateLightingMessage::has_high_beam() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void StateLightingMessage::set_has_high_beam() {
  _has_bits_[0] |= 0x00000002u;
}
inline void StateLightingMessage::clear_has_high_beam() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void StateLightingMessage::clear_high_beam() {
  high_beam_ = 0;
  clear_has_high_beam();
}
inline ::google::protobuf::int32 StateLightingMessage::high_beam() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.high_beam)
  return high_beam_;
}
inline void StateLightingMessage::set_high_beam(::google::protobuf::int32 value) {
  set_has_high_beam();
  high_beam_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.high_beam)
}

// optional int32 left_cornering_lamp = 4;
inline bool StateLightingMessage::has_left_cornering_lamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void StateLightingMessage::set_has_left_cornering_lamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void StateLightingMessage::clear_has_left_cornering_lamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void StateLightingMessage::clear_left_cornering_lamp() {
  left_cornering_lamp_ = 0;
  clear_has_left_cornering_lamp();
}
inline ::google::protobuf::int32 StateLightingMessage::left_cornering_lamp() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.left_cornering_lamp)
  return left_cornering_lamp_;
}
inline void StateLightingMessage::set_left_cornering_lamp(::google::protobuf::int32 value) {
  set_has_left_cornering_lamp();
  left_cornering_lamp_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.left_cornering_lamp)
}

// optional int32 right_cornering_lamp = 6;
inline bool StateLightingMessage::has_right_cornering_lamp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void StateLightingMessage::set_has_right_cornering_lamp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void StateLightingMessage::clear_has_right_cornering_lamp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void StateLightingMessage::clear_right_cornering_lamp() {
  right_cornering_lamp_ = 0;
  clear_has_right_cornering_lamp();
}
inline ::google::protobuf::int32 StateLightingMessage::right_cornering_lamp() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.right_cornering_lamp)
  return right_cornering_lamp_;
}
inline void StateLightingMessage::set_right_cornering_lamp(::google::protobuf::int32 value) {
  set_has_right_cornering_lamp();
  right_cornering_lamp_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.right_cornering_lamp)
}

// optional int32 clearance_light = 8;
inline bool StateLightingMessage::has_clearance_light() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void StateLightingMessage::set_has_clearance_light() {
  _has_bits_[0] |= 0x00000010u;
}
inline void StateLightingMessage::clear_has_clearance_light() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void StateLightingMessage::clear_clearance_light() {
  clearance_light_ = 0;
  clear_has_clearance_light();
}
inline ::google::protobuf::int32 StateLightingMessage::clearance_light() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.clearance_light)
  return clearance_light_;
}
inline void StateLightingMessage::set_clearance_light(::google::protobuf::int32 value) {
  set_has_clearance_light();
  clearance_light_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.clearance_light)
}

// optional int32 fog_light = 10;
inline bool StateLightingMessage::has_fog_light() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void StateLightingMessage::set_has_fog_light() {
  _has_bits_[0] |= 0x00000020u;
}
inline void StateLightingMessage::clear_has_fog_light() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void StateLightingMessage::clear_fog_light() {
  fog_light_ = 0;
  clear_has_fog_light();
}
inline ::google::protobuf::int32 StateLightingMessage::fog_light() const {
  // @@protoc_insertion_point(field_get:StateLightingMessage.fog_light)
  return fog_light_;
}
inline void StateLightingMessage::set_fog_light(::google::protobuf::int32 value) {
  set_has_fog_light();
  fog_light_ = value;
  // @@protoc_insertion_point(field_set:StateLightingMessage.fog_light)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_state_5flighting_2eproto__INCLUDED
